const SOCKET_CLIENT_SEND_PROFILE = "SOCKET_CLIENT_SEND_PROFILE";

const SOCKET_CLIENT_SEND_NEW_POST = "SOCKET_CLIENT_SEND_NEW_POST";
const SOCKET_SERVER_SEND_NEW_POST = "SOCKET_SERVER_SEND_NEW_POST";

const SOCKET_CLIENT_SEND_JOIN_ROOM_POST = "SOCKET_CLIENT_SEND_JOIN_ROOM_POST";
const SOCKET_CLIENT_SEND_LEAVE_ROOM_POST = "SOCKET_CLIENT_SEND_LEAVE_ROOM_POST";

const SOCKET_CLIENT_SEND_USER_FOCUS_POSTCOMMENT =
	"SOCKET_CLIENT_SEND_USER_FOCUS_POSTCOMMENT";
const SOCKET_SERVER_SEND_USER_FOCUS_POSTCOMMENT =
	"SOCKET_SERVER_SEND_USER_FOCUS_POSTCOMMENT";
const SOCKET_CLIENT_SEND_USER_UNFOCUS_POSTCOMMENT =
	"SOCKET_CLIENT_SEND_USER_UNFOCUS_POSTCOMMENT";
const SOCKET_SERVER_SEND_USER_UNFOCUS_POSTCOMMENT =
	"SOCKET_SERVER_SEND_USER_UNFOCUS_POSTCOMMENT";

const SOCKET_CLIENT_SEND_NEW_POSTCOMMENT = "SOCKET_CLIENT_SEND_NEW_POSTCOMMENT";
const SOCKET_SERVER_SEND_NEW_POSTCOMMENT = "SOCKET_SERVER_SEND_NEW_POSTCOMMENT";

const SOCKET_CLIENT_SEND_MEMBER_COMMENT_POST =
	"SOCKET_CLIENT_SEND_MEMBER_COMMENT_POST";
const SOCKET_SERVER_SEND_MEMBER_COMMENT_POST =
	"SOCKET_SERVER_SEND_MEMBER_COMMENT_POST";

module.exports = {
	SOCKET_CLIENT_SEND_PROFILE,
	SOCKET_CLIENT_SEND_NEW_POST,
	SOCKET_SERVER_SEND_NEW_POST,
	SOCKET_CLIENT_SEND_JOIN_ROOM_POST,
	SOCKET_CLIENT_SEND_LEAVE_ROOM_POST,
	SOCKET_CLIENT_SEND_USER_FOCUS_POSTCOMMENT,
	SOCKET_SERVER_SEND_USER_FOCUS_POSTCOMMENT,
	SOCKET_CLIENT_SEND_USER_UNFOCUS_POSTCOMMENT,
	SOCKET_SERVER_SEND_USER_UNFOCUS_POSTCOMMENT,
	SOCKET_CLIENT_SEND_NEW_POSTCOMMENT,
	SOCKET_SERVER_SEND_NEW_POSTCOMMENT,
	SOCKET_CLIENT_SEND_MEMBER_COMMENT_POST,
	SOCKET_SERVER_SEND_MEMBER_COMMENT_POST,
};
